/** Ethiopian banks for KYC bank selection (alphabetical). */
export const ETHIOPIAN_BANKS: readonly string[] = [
  "Abay Bank",
  "Addis International Bank",
  "Ahadu Bank",
  "Amhara Bank",
  "Awash Bank",
  "Bank of Abyssinia",
  "Berhan Bank",
  "Bunna Bank",
  "Commercial Bank of Ethiopia (CBE)",
  "Cooperative Bank of Oromia",
  "Dashen Bank",
  "Development Bank of Ethiopia (DBE)",
  "Enat Bank",
  "Gadaa Bank",
  "Global Bank Ethiopia",
  "Goh Betoch Bank",
  "Hibret Bank",
  "Lion Bank",
  "Nib International Bank",
  "Omo Bank",
  "Oromia Bank",
  "Rammis Bank",
  "Shabelle Bank",
  "Sidama Bank",
  "Siinqee Bank",
  "Siket Bank",
  "Tsedey Bank",
  "Wegagen Bank",
  "Zemen Bank",
] as const;
